#pragma config(Motor,  motorC,          ,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code autobmatically generated by 'ROBOTC' configuration wizard               !!*//

#include "include/includes.h"

task main(){
    changePosGrabberC(10, 180);
    waitGrabberC();
    //sleep(3000);
}
