#define RUN_ONLY_TEST_FUNCTION 0
#define CALIBRATION 0
#define CALIBRATE_SEN1_COLOR_DETECTION 0
#define CALIBRATE_SEN2_COLOR_DETECTION 0
#define CALIBRATE_SEN3_COLOR_DETECTION 0
#define DETECT_FROM_LINE_SEN3 0